# -*- coding: utf-8 -*-
"""modelling_winner.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ULGITSfWQXLju6WZM6t1MD0AnqT4wIY9
"""

from google.colab import drive
drive.mount('/content/gdrive')

import pandas as pd

from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder, LabelBinarizer
from sklearn_pandas import DataFrameMapper
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

df = pd.read_csv('gdrive/My Drive/Colab Notebooks/data/games_updated.csv')
pd.set_option('display.max_columns', None)

df.head(2)

del df["Unnamed: 0"]

target = 'winner'
y = df[target]
X = df.drop(target, axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

mapper = DataFrameMapper([
    (['white_rating'], StandardScaler()),                    
    (['black_rating'], StandardScaler()),
    (['turns'], StandardScaler()),
    ('opening_eco', LabelBinarizer()),
    ('opening_name', LabelBinarizer()),
    ('firstplay', LabelBinarizer()),
    ('secondplay', LabelBinarizer()),
    ('thirdplay', LabelBinarizer()),
    ('fourthplay', LabelBinarizer()),
    ('fifthplay', LabelBinarizer()),
    ('sixthplay', LabelBinarizer()),
    ('seventhplay', LabelBinarizer()),
    ('eighthplay', LabelBinarizer()),
    ('ninthplay', LabelBinarizer()),
    ('tenthplay', LabelBinarizer()),
#    ('eleventhplay', LabelBinarizer()),
#    ('twelvthplay', LabelBinarizer()),
#    ('thirteenthplay', LabelBinarizer()),
#    ('fourteenthplay', LabelBinarizer()),
#    ('fifteenthplay', LabelBinarizer()),
#    ('sixteenthplay', LabelBinarizer()),
#    ('seventhplay', LabelBinarizer()),
#    ('eigteenthplay', LabelBinarizer()),
#    ('nineteenthplay', LabelBinarizer()),
#    ('twentythplay', LabelBinarizer())
    ],df_out=True)

Z_train = mapper.fit_transform(X_train)
Z_test = mapper.transform(X_test)

model = LogisticRegression().fit(Z_train,y_train)
model.score(Z_train,y_train)

model.score(Z_test,y_test)

model = RandomForestClassifier().fit(Z_train,y_train)
model.score(Z_train,y_train)

model.score(Z_test,y_test)

model = DecisionTreeClassifier().fit(Z_train,y_train)
model.score(Z_train,y_train)

model.score(Z_test,y_test)

model = LogisticRegression()

params = {
    "penalty": ["l1", "l2", "elasticnet", None], 
    "dual": [False, True], 
    "max_iter": [50, 100, 150, 200], 
    "multi_class": ['auto'], 
    "warm_start": [False, True] 
}

grid = GridSearchCV(model, params, cv=3, n_jobs=-1, verbose=1)

grid.fit(Z_train, y_train)

grid.best_score_

grid.best_params_

